import React, { useMemo } from 'react';
import { StyleSheet } from 'react-native';

import { useNavigation } from '@react-navigation/native';
import useFeatureFlags from '../../../../hooks/featureFlags/useFeatureFlags';
import TemplateBox from '../../../../components/TemplateBox';
import { SCREEN_WIDTH, WRAPPER_MARGIN } from '../../../../theme/Layout';
import FeedCard from './FeedCard';
import { BLACK } from '../../../../theme/Colors';
import TemplateText from '../../../../components/TemplateText';
import { FEED_DETAILS } from '../../../../navigation/ScreenNames';

const getIconByType = (type) => {
    if (type === 'ideas') {
        return 'trending-up-outline';
    } if (type === 'tips') {
        return 'rocket-outline';
    } if (type === 'videoLessons') {
        return 'videocam-outline';
    } if (type === 'hooks') {
        return 'reader-outline';
    } if (type === 'photoEditing') {
        return 'camera-outline';
    } if (type === 'ctaTips') {
        return 'bar-chart-outline';
    }
    return 'article';
};

const FeedsTab = () => {
    const { feed } = useFeatureFlags();

    const navigation = useNavigation();

    const filteredFeed = useMemo(() => {
        if (!feed?.feeds?.length) return [];

        return feed?.feeds;
    }, [feed]);

    return (
        <TemplateBox ph={WRAPPER_MARGIN + 4}>
            <TemplateText size={15} color={BLACK} style={styles.subtitle}>
                {/* eslint-disable-next-line max-len */}
                Check out weekly content updates, these include:
                { '\n'}
                general tips, hooks examples, photo/video editing tips,
                video lessons and ideas all generated by AI based on your
                portfolio.
            </TemplateText>
            {
                filteredFeed && filteredFeed?.map((item, index) => (
                    <FeedCard
                        key={`feed-${index}`}
                        image={{ uri: item?.thumbnail }}
                        title={item?.title}
                        icon={getIconByType(item?.type)}
                        subtitle={item?.subtitle}
                        shortDescription={item?.description}
                        style={styles.card}
                        showGradient
                        cardWidth={SCREEN_WIDTH / 1.12}
                        aspectRatio={1.8}
                        slideInDelay={(index + 1) * 100}
                        onPress={() => {
                            navigation.navigate(FEED_DETAILS, {
                                selectedFeed: item,
                            });
                        }}
                    />
                ))
            }
        </TemplateBox>
    );
};

const styles = StyleSheet.create({
    card: {
        marginBottom: WRAPPER_MARGIN,
        alignSelf: 'center',
    },
    subtitle: {

        marginBottom: 10,
    },
});
export default FeedsTab;
